// This file originates from the SatoshiLabs Trezor `common` repository at:
//   https://github.com/trezor/trezor-common/blob/master/protob/messages-ethereum.proto
// dated 28.05.2019, commit 893fd219d4a01bcffa0cd9cfa631856371ec5aa9.
// Adapted for SILA Blockchain

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: messages-ethereum.proto

package trezor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Request: Ask device for public key corresponding to address_n path
// @start
// @next SILAPublicKey
// @next Failure
type SILAGetPublicKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddressN      []uint32               `protobuf:"varint,1,rep,name=address_n,json=addressN" json:"address_n,omitempty"`          // BIP-32 path to derive the key from master node
	ShowDisplay   *bool                  `protobuf:"varint,2,opt,name=show_display,json=showDisplay" json:"show_display,omitempty"` // optionally show on display before sending the result
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SILAGetPublicKey) Reset() {
	*x = SILAGetPublicKey{}
	mi := &file_messages_ethereum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SILAGetPublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SILAGetPublicKey) ProtoMessage() {}

func (x *SILAGetPublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_messages_ethereum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SILAGetPublicKey.ProtoReflect.Descriptor instead.
func (*SILAGetPublicKey) Descriptor() ([]byte, []int) {
	return file_messages_ethereum_proto_rawDescGZIP(), []int{0}
}

func (x *SILAGetPublicKey) GetAddressN() []uint32 {
	if x != nil {
		return x.AddressN
	}
	return nil
}

func (x *SILAGetPublicKey) GetShowDisplay() bool {
	if x != nil && x.ShowDisplay != nil {
		return *x.ShowDisplay
	}
	return false
}

// *
// Response: Contains public key derived from device private seed
// @end
type SILAPublicKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *HDNodeType            `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"` // BIP32 public node
	Xpub          *string                `protobuf:"bytes,2,opt,name=xpub" json:"xpub,omitempty"` // serialized form of public node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SILAPublicKey) Reset() {
	*x = SILAPublicKey{}
	mi := &file_messages_ethereum_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SILAPublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SILAPublicKey) ProtoMessage() {}

func (x *SILAPublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_messages_ethereum_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SILAPublicKey.ProtoReflect.Descriptor instead.
func (*SILAPublicKey) Descriptor() ([]byte, []int) {
	return file_messages_ethereum_proto_rawDescGZIP(), []int{1}
}

func (x *SILAPublicKey) GetNode() *HDNodeType {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *SILAPublicKey) GetXpub() string {
	if x != nil && x.Xpub != nil {
		return *x.Xpub
	}
	return ""
}

// *
// Request: Ask device for SILA address corresponding to address_n path
// @start
// @next SILAAddress
// @next Failure
type SILAGetAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddressN      []uint32               `protobuf:"varint,1,rep,name=address_n,json=addressN" json:"address_n,omitempty"`          // BIP-32 path to derive the key from master node
	ShowDisplay   *bool                  `protobuf:"varint,2,opt,name=show_display,json=showDisplay" json:"show_display,omitempty"` // optionally show on display before sending the result
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SILAGetAddress) Reset() {
	*x = SILAGetAddress{}
	mi := &file_messages_ethereum_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SILAGetAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SILAGetAddress) ProtoMessage() {}

func (x *SILAGetAddress) ProtoReflect() protoreflect.Message {
	mi := &file_messages_ethereum_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SILAGetAddress.ProtoReflect.Descriptor instead.
func (*SILAGetAddress) Descriptor() ([]byte, []int) {
	return file_messages_ethereum_proto_rawDescGZIP(), []int{2}
}

func (x *SILAGetAddress) GetAddressN() []uint32 {
	if x != nil {
		return x.AddressN
	}
	return nil
}

func (x *SILAGetAddress) GetShowDisplay() bool {
	if x != nil && x.ShowDisplay != nil {
		return *x.ShowDisplay
	}
	return false
}

// *
// Response: Contains a SILA address derived from device private seed
// @end
type SILAAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddressBin    []byte                 `protobuf:"bytes,1,opt,name=addressBin" json:"addressBin,omitempty"` // SILA address as 20 bytes (legacy firmwares)
	AddressHex    *string                `protobuf:"bytes,2,opt,name=addressHex" json:"addressHex,omitempty"` // SILA address as hex string (newer firmwares)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SILAAddress) Reset() {
	*x = SILAAddress{}
	mi := &file_messages_ethereum_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SILAAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SILAAddress) ProtoMessage() {}

func (x *SILAAddress) ProtoReflect() protoreflect.Message {
	mi := &file_messages_ethereum_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SILAAddress.ProtoReflect.Descriptor instead.
func (*SILAAddress) Descriptor() ([]byte, []int) {
	return file_messages_ethereum_proto_rawDescGZIP(), []int{3}
}

func (x *SILAAddress) GetAddressBin() []byte {
	if x != nil {
		return x.AddressBin
	}
	return nil
}

func (x *SILAAddress) GetAddressHex() string {
	if x != nil && x.AddressHex != nil {
		return *x.AddressHex
	}
	return ""
}

// *
// Request: Ask device to sign transaction
// All fields are optional from the protocol's point of view. Each field defaults to value `0` if missing.
// Note: the first at most 1024 bytes of data MUST be transmitted as part of this message.
// @start
// @next SILATxRequest
// @next Failure
type SILASignTx struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AddressN         []uint32               `protobuf:"varint,1,rep,name=address_n,json=addressN" json:"address_n,omitempty"`                          // BIP-32 path to derive the key from master node
	Nonce            []byte                 `protobuf:"bytes,2,opt,name=nonce" json:"nonce,omitempty"`                                                 // <=256 bit unsigned big endian
	GasPrice         []byte                 `protobuf:"bytes,3,opt,name=gas_price,json=gasPrice" json:"gas_price,omitempty"`                           // <=256 bit unsigned big endian (in wei)
	GasLimit         []byte                 `protobuf:"bytes,4,opt,name=gas_limit,json=gasLimit" json:"gas_limit,omitempty"`                           // <=256 bit unsigned big endian
	ToBin            []byte                 `protobuf:"bytes,5,opt,name=toBin" json:"toBin,omitempty"`                                                 // recipient address (20 bytes, legacy firmware)
	ToHex            *string                `protobuf:"bytes,11,opt,name=toHex" json:"toHex,omitempty"`                                                // recipient address (hex string, newer firmware)
	Value            []byte                 `protobuf:"bytes,6,opt,name=value" json:"value,omitempty"`                                                 // <=256 bit unsigned big endian (in wei)
	DataInitialChunk []byte                 `protobuf:"bytes,7,opt,name=data_initial_chunk,json=dataInitialChunk" json:"data_initial_chunk,omitempty"` // The initial data chunk (<= 1024 bytes)
	DataLength       *uint32                `protobuf:"varint,8,opt,name=data_length,json=dataLength" json:"data_length,omitempty"`                    // Length of transaction payload
	ChainId          *uint32                `protobuf:"varint,9,opt,name=chain_id,json=chainId" json:"chain_id,omitempty"`                             // Chain Id for EIP 155
	TxType           *uint32                `protobuf:"varint,10,opt,name=tx_type,json=txType" json:"tx_type,omitempty"`                               // (only for Wanchain)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SILASignTx) Reset() {
	*x = SILASignTx{}
	mi := &file_messages_ethereum_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SILASignTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SILASignTx) ProtoMessage() {}

func (x *SILASignTx) ProtoReflect() protoreflect.Message {
	mi := &file_messages_ethereum_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SILASignTx.ProtoReflect.Descriptor instead.
func (*SILASignTx) Descriptor() ([]byte, []int) {
	return file_messages_ethereum_proto_rawDescGZIP(), []int{4}
}

func (x *SILASignTx) GetAddressN() []uint32 {
	if x != nil {
		return x.AddressN
	}
	return nil
}

func (x *SILASignTx) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *SILASignTx) GetGasPrice() []byte {
	if x != nil {
		return x.GasPrice
	}
	return nil
}

func (x *SILASignTx) GetGasLimit() []byte {
	if x != nil {
		return x.GasLimit
	}
	return nil
}

func (x *SILASignTx) GetToBin() []byte {
	if x != nil {
		return x.ToBin
	}
	return nil
}

func (x *SILASignTx) GetToHex() string {
	if x != nil && x.ToHex != nil {
		return *x.ToHex
	}
	return ""
}

func (x *SILASignTx) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SILASignTx) GetDataInitialChunk() []byte {
	if x != nil {
		return x.DataInitialChunk
	}
	return nil
}

func (x *SILASignTx) GetDataLength() uint32 {
	if x != nil && x.DataLength != nil {
		return *x.DataLength
	}
	return 0
}

func (x *SILASignTx) GetChainId() uint32 {
	if x != nil && x.ChainId != nil {
		return *x.ChainId
	}
	return 0
}

func (x *SILASignTx) GetTxType() uint32 {
	if x != nil && x.TxType != nil {
		return *x.TxType
	}
	return 0
}

// *
// Response: Device asks for more data from transaction payload, or returns the signature.
// If data_length is set, device awaits that many more bytes of payload.
// Otherwise, the signature_* fields contain the computed transaction signature. All three fields will be present.
// @end
// @next SILATxAck
type SILATxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataLength    *uint32                `protobuf:"varint,1,opt,name=data_length,json=dataLength" json:"data_length,omitempty"` // Number of bytes being requested (<= 1024)
	SignatureV    *uint32                `protobuf:"varint,2,opt,name=signature_v,json=signatureV" json:"signature_v,omitempty"` // Computed signature (recovery parameter, limited to 27 or 28)
	SignatureR    []byte                 `protobuf:"bytes,3,opt,name=signature_r,json=signatureR" json:"signature_r,omitempty"`  // Computed signature R component (256 bit)
	SignatureS    []byte                 `protobuf:"bytes,4,opt,name=signature_s,json=signatureS" json:"signature_s,omitempty"`  // Computed signature S component (256 bit)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SILATxRequest) Reset() {
	*x = SILATxRequest{}
	mi := &file_messages_ethereum_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SILATxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SILATxRequest) ProtoMessage() {}

func (x *SILATxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_ethereum_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SILATxRequest.ProtoReflect.Descriptor instead.
func (*SILATxRequest) Descriptor() ([]byte, []int) {
	return file_messages_ethereum_proto_rawDescGZIP(), []int{5}
}

func (x *SILATxRequest) GetDataLength() uint32 {
	if x != nil && x.DataLength != nil {
		return *x.DataLength
	}
	return 0
}

func (x *SILATxRequest) GetSignatureV() uint32 {
	if x != nil && x.SignatureV != nil {
		return *x.SignatureV
	}
	return 0
}

func (x *SILATxRequest) GetSignatureR() []byte {
	if x != nil {
		return x.SignatureR
	}
	return nil
}

func (x *SILATxRequest) GetSignatureS() []byte {
	if x != nil {
		return x.SignatureS
	}
	return nil
}

// *
// Request: Transaction payload data.
// @next SILATxRequest
type SILATxAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataChunk     []byte                 `protobuf:"bytes,1,opt,name=data_chunk,json=dataChunk" json:"data_chunk,omitempty"` // Bytes from transaction payload (<= 1024 bytes)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SILATxAck) Reset() {
	*x = SILATxAck{}
	mi := &file_messages_ethereum_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SILATxAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SILATxAck) ProtoMessage() {}

func (x *SILATxAck) ProtoReflect() protoreflect.Message {
	mi := &file_messages_ethereum_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SILATxAck.ProtoReflect.Descriptor instead.
func (*SILATxAck) Descriptor() ([]byte, []int) {
	return file_messages_ethereum_proto_rawDescGZIP(), []int{6}
}

func (x *SILATxAck) GetDataChunk() []byte {
	if x != nil {
		return x.DataChunk
	}
	return nil
}

// *
// Request: Ask device to sign message
// @start
// @next SILAMessageSignature
// @next Failure
type SILASignMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddressN      []uint32               `protobuf:"varint,1,rep,name=address_n,json=addressN" json:"address_n,omitempty"` // BIP-32 path to derive the key from master node
	Message       []byte                 `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`                    // message to be signed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SILASignMessage) Reset() {
	*x = SILASignMessage{}
	mi := &file_messages_ethereum_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SILASignMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SILASignMessage) ProtoMessage() {}

func (x *SILASignMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_ethereum_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SILASignMessage.ProtoReflect.Descriptor instead.
func (*SILASignMessage) Descriptor() ([]byte, []int) {
	return file_messages_ethereum_proto_rawDescGZIP(), []int{7}
}

func (x *SILASignMessage) GetAddressN() []uint32 {
	if x != nil {
		return x.AddressN
	}
	return nil
}

func (x *SILASignMessage) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

// *
// Response: Signed message
// @end
type SILAMessageSignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddressBin    []byte                 `protobuf:"bytes,1,opt,name=addressBin" json:"addressBin,omitempty"` // address used to sign the message (20 bytes, legacy firmware)
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`   // signature of the message
	AddressHex    *string                `protobuf:"bytes,3,opt,name=addressHex" json:"addressHex,omitempty"` // address used to sign the message (hex string, newer firmware)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SILAMessageSignature) Reset() {
	*x = SILAMessageSignature{}
	mi := &file_messages_ethereum_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SILAMessageSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SILAMessageSignature) ProtoMessage() {}

func (x *SILAMessageSignature) ProtoReflect() protoreflect.Message {
	mi := &file_messages_ethereum_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SILAMessageSignature.ProtoReflect.Descriptor instead.
func (*SILAMessageSignature) Descriptor() ([]byte, []int) {
	return file_messages_ethereum_proto_rawDescGZIP(), []int{8}
}

func (x *SILAMessageSignature) GetAddressBin() []byte {
	if x != nil {
		return x.AddressBin
	}
	return nil
}

func (x *SILAMessageSignature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SILAMessageSignature) GetAddressHex() string {
	if x != nil && x.AddressHex != nil {
		return *x.AddressHex
	}
	return ""
}

// *
// Request: Ask device to verify message
// @start
// @next Success
// @next Failure
type SILAVerifyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddressBin    []byte                 `protobuf:"bytes,1,opt,name=addressBin" json:"addressBin,omitempty"` // address to verify (20 bytes, legacy firmware)
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`   // signature to verify
	Message       []byte                 `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`       // message to verify
	AddressHex    *string                `protobuf:"bytes,4,opt,name=addressHex" json:"addressHex,omitempty"` // address to verify (hex string, newer firmware)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SILAVerifyMessage) Reset() {
	*x = SILAVerifyMessage{}
	mi := &file_messages_ethereum_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SILAVerifyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SILAVerifyMessage) ProtoMessage() {}

func (x *SILAVerifyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_ethereum_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SILAVerifyMessage.ProtoReflect.Descriptor instead.
func (*SILAVerifyMessage) Descriptor() ([]byte, []int) {
	return file_messages_ethereum_proto_rawDescGZIP(), []int{9}
}

func (x *SILAVerifyMessage) GetAddressBin() []byte {
	if x != nil {
		return x.AddressBin
	}
	return nil
}

func (x *SILAVerifyMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SILAVerifyMessage) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SILAVerifyMessage) GetAddressHex() string {
	if x != nil && x.AddressHex != nil {
		return *x.AddressHex
	}
	return ""
}

var File_messages_ethereum_proto protoreflect.FileDescriptor

const file_messages_ethereum_proto_rawDesc = "" +
	"\n" +
	"\x17messages-ethereum.proto\x12\x17hw.trezor.messages.sila\x1a\x15messages-common.proto\"R\n" +
	"\x10SILAGetPublicKey\x12\x1b\n" +
	"\taddress_n\x18\x01 \x03(\rR\baddressN\x12!\n" +
	"\fshow_display\x18\x02 \x01(\bR\vshowDisplay\"^\n" +
	"\rSILAPublicKey\x129\n" +
	"\x04node\x18\x01 \x01(\v2%.hw.trezor.messages.common.HDNodeTypeR\x04node\x12\x12\n" +
	"\x04xpub\x18\x02 \x01(\tR\x04xpub\"P\n" +
	"\x0eSILAGetAddress\x12\x1b\n" +
	"\taddress_n\x18\x01 \x03(\rR\baddressN\x12!\n" +
	"\fshow_display\x18\x02 \x01(\bR\vshowDisplay\"M\n" +
	"\vSILAAddress\x12\x1e\n" +
	"\n" +
	"addressBin\x18\x01 \x01(\fR\n" +
	"addressBin\x12\x1e\n" +
	"\n" +
	"addressHex\x18\x02 \x01(\tR\n" +
	"addressHex\"\xbe\x02\n" +
	"\n" +
	"SILASignTx\x12\x1b\n" +
	"\taddress_n\x18\x01 \x03(\rR\baddressN\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12\x1b\n" +
	"\tgas_price\x18\x03 \x01(\fR\bgasPrice\x12\x1b\n" +
	"\tgas_limit\x18\x04 \x01(\fR\bgasLimit\x12\x14\n" +
	"\x05toBin\x18\x05 \x01(\fR\x05toBin\x12\x14\n" +
	"\x05toHex\x18\v \x01(\tR\x05toHex\x12\x14\n" +
	"\x05value\x18\x06 \x01(\fR\x05value\x12,\n" +
	"\x12data_initial_chunk\x18\a \x01(\fR\x10dataInitialChunk\x12\x1f\n" +
	"\vdata_length\x18\b \x01(\rR\n" +
	"dataLength\x12\x19\n" +
	"\bchain_id\x18\t \x01(\rR\achainId\x12\x17\n" +
	"\atx_type\x18\n" +
	" \x01(\rR\x06txType\"\x93\x01\n" +
	"\rSILATxRequest\x12\x1f\n" +
	"\vdata_length\x18\x01 \x01(\rR\n" +
	"dataLength\x12\x1f\n" +
	"\vsignature_v\x18\x02 \x01(\rR\n" +
	"signatureV\x12\x1f\n" +
	"\vsignature_r\x18\x03 \x01(\fR\n" +
	"signatureR\x12\x1f\n" +
	"\vsignature_s\x18\x04 \x01(\fR\n" +
	"signatureS\"*\n" +
	"\tSILATxAck\x12\x1d\n" +
	"\n" +
	"data_chunk\x18\x01 \x01(\fR\tdataChunk\"H\n" +
	"\x0fSILASignMessage\x12\x1b\n" +
	"\taddress_n\x18\x01 \x03(\rR\baddressN\x12\x18\n" +
	"\amessage\x18\x02 \x01(\fR\amessage\"t\n" +
	"\x14SILAMessageSignature\x12\x1e\n" +
	"\n" +
	"addressBin\x18\x01 \x01(\fR\n" +
	"addressBin\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x1e\n" +
	"\n" +
	"addressHex\x18\x03 \x01(\tR\n" +
	"addressHex\"\x8b\x01\n" +
	"\x11SILAVerifyMessage\x12\x1e\n" +
	"\n" +
	"addressBin\x18\x01 \x01(\fR\n" +
	"addressBin\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x18\n" +
	"\amessage\x18\x03 \x01(\fR\amessage\x12\x1e\n" +
	"\n" +
	"addressHex\x18\x04 \x01(\tR\n" +
	"addressHexB{\n" +
	"#com.satoshilabs.trezor.lib.protobufB\x11TrezorMessageSILAZAgithub.com/sila-blockchain/sila-library/accounts/usbwallet/trezor"

var (
	file_messages_ethereum_proto_rawDescOnce sync.Once
	file_messages_ethereum_proto_rawDescData []byte
)

func file_messages_ethereum_proto_rawDescGZIP() []byte {
	file_messages_ethereum_proto_rawDescOnce.Do(func() {
		file_messages_ethereum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_ethereum_proto_rawDesc), len(file_messages_ethereum_proto_rawDesc)))
	})
	return file_messages_ethereum_proto_rawDescData
}

var file_messages_ethereum_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_messages_ethereum_proto_goTypes = []any{
	(*SILAGetPublicKey)(nil),     // 0: hw.trezor.messages.sila.SILAGetPublicKey
	(*SILAPublicKey)(nil),        // 1: hw.trezor.messages.sila.SILAPublicKey
	(*SILAGetAddress)(nil),       // 2: hw.trezor.messages.sila.SILAGetAddress
	(*SILAAddress)(nil),          // 3: hw.trezor.messages.sila.SILAAddress
	(*SILASignTx)(nil),           // 4: hw.trezor.messages.sila.SILASignTx
	(*SILATxRequest)(nil),        // 5: hw.trezor.messages.sila.SILATxRequest
	(*SILATxAck)(nil),            // 6: hw.trezor.messages.sila.SILATxAck
	(*SILASignMessage)(nil),      // 7: hw.trezor.messages.sila.SILASignMessage
	(*SILAMessageSignature)(nil), // 8: hw.trezor.messages.sila.SILAMessageSignature
	(*SILAVerifyMessage)(nil),    // 9: hw.trezor.messages.sila.SILAVerifyMessage
	(*HDNodeType)(nil),           // 10: hw.trezor.messages.common.HDNodeType
}
var file_messages_ethereum_proto_depIdxs = []int32{
	10, // 0: hw.trezor.messages.sila.SILAPublicKey.node:type_name -> hw.trezor.messages.common.HDNodeType
	1,  // [1:1] is the sub-list for method output_type
	1,  // [1:1] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_messages_ethereum_proto_init() }
func file_messages_ethereum_proto_init() {
	if File_messages_ethereum_proto != nil {
		return
	}
	file_messages_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_ethereum_proto_rawDesc), len(file_messages_ethereum_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_ethereum_proto_goTypes,
		DependencyIndexes: file_messages_ethereum_proto_depIdxs,
		MessageInfos:      file_messages_ethereum_proto_msgTypes,
	}.Build()
	File_messages_ethereum_proto = out.File
	file_messages_ethereum_proto_goTypes = nil
	file_messages_ethereum_proto_depIdxs = nil
}
