// Copyright 2026 The SILA Authors
// This file is part of the sila-library.
//
// The sila-library is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// The sila-library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with the sila-library. If not, see <http://www.gnu.org/licenses/>.

package filtermaps

import (
	"context"

	"silachain/common"
	"silachain/core/types"
)

// FilterMapsMatcherBackend implements MatcherBackend.
type FilterMapsMatcherBackend struct {
	f *FilterMaps

	validBlocks common.Range[uint64]
	syncCh      chan SyncRange
}

// NewMatcherBackend returns a FilterMapsMatcherBackend after registering it in
// the active matcher set.
func (f *FilterMaps) NewMatcherBackend() *FilterMapsMatcherBackend {
	f.indexLock.RLock()
	f.matchersLock.Lock()
	defer func() {
		f.matchersLock.Unlock()
		f.indexLock.RUnlock()
	}()

	fm := &FilterMapsMatcherBackend{f: f}
	if f.indexedRange.initialized {
		fm.validBlocks = f.indexedRange.blocks
	}
	f.matchers[fm] = struct{}{}
	return fm
}

// GetParams returns the filtermaps parameters.
func (fm *FilterMapsMatcherBackend) GetParams() *Params {
	return &fm.f.Params
}

// Close removes the matcher from the set of active matchers.
func (fm *FilterMapsMatcherBackend) Close() {
	fm.f.matchersLock.Lock()
	defer fm.f.matchersLock.Unlock()

	delete(fm.f.matchers, fm)
}

// GetFilterMapRows returns the given row of the given map.
func (fm *FilterMapsMatcherBackend) GetFilterMapRows(ctx context.Context, mapIndices []uint32, rowIndex uint32, baseLayerOnly bool) ([]FilterRow, error) {
	return fm.f.getFilterMapRows(mapIndices, rowIndex, baseLayerOnly)
}

// GetBlockLvPointer returns the starting log value index where the log values
// generated by the given block are located.
func (fm *FilterMapsMatcherBackend) GetBlockLvPointer(ctx context.Context, blockNumber uint64) (uint64, error) {
	fm.f.indexLock.RLock()
	defer fm.f.indexLock.RUnlock()

	if blockNumber >= fm.f.indexedRange.blocks.AfterLast() {
		if fm.f.indexedRange.headIndexed {
			return fm.f.indexedRange.headDelimiter + 1, nil
		}
		if fm.f.indexedRange.blocks.Count() > 0 {
			blockNumber = fm.f.indexedRange.blocks.Last()
		}
	}
	return fm.f.getBlockLvPointer(blockNumber)
}

// GetLogByLvIndex returns the log at the given log value index.
func (fm *FilterMapsMatcherBackend) GetLogByLvIndex(ctx context.Context, lvIndex uint64) (*types.Log, error) {
	fm.f.indexLock.RLock()
	defer fm.f.indexLock.RUnlock()

	return fm.f.getLogByLvIndex(lvIndex)
}

// synced signals to the matcher that has triggered a synchronisation that it
// has been finished.
func (fm *FilterMapsMatcherBackend) synced() {
	fm.f.matchersLock.Lock()
	defer fm.f.matchersLock.Unlock()

	indexedBlocks := fm.f.indexedRange.blocks
	if !fm.f.indexedRange.headIndexed && !indexedBlocks.IsEmpty() {
		indexedBlocks.SetAfterLast(indexedBlocks.Last())
	}
	fm.syncCh <- SyncRange{
		IndexedView:   fm.f.indexedView,
		ValidBlocks:   fm.validBlocks,
		IndexedBlocks: indexedBlocks,
	}
	fm.validBlocks = indexedBlocks
	fm.syncCh = nil
}

// SyncLogIndex ensures that the log index is consistent with the current state
// of the chain and is synced up to the current head.
func (fm *FilterMapsMatcherBackend) SyncLogIndex(ctx context.Context) (SyncRange, error) {
	syncCh := make(chan SyncRange, 1)
	fm.f.matchersLock.Lock()
	fm.syncCh = syncCh
	fm.f.matchersLock.Unlock()

	select {
	case fm.f.matcherSyncCh <- fm:
	case <-ctx.Done():
		return SyncRange{}, ctx.Err()
	case <-fm.f.disabledCh:
		return SyncRange{IndexedView: fm.f.indexedView}, nil
	}
	select {
	case vr := <-syncCh:
		return vr, nil
	case <-ctx.Done():
		return SyncRange{}, ctx.Err()
	case <-fm.f.disabledCh:
		return SyncRange{IndexedView: fm.f.indexedView}, nil
	}
}

// updateMatchersValidRange iterates through active matchers and limits their
// valid range with the current indexed range.
func (f *FilterMaps) updateMatchersValidRange() {
	f.matchersLock.Lock()
	defer f.matchersLock.Unlock()

	for fm := range f.matchers {
		if !f.indexedRange.initialized {
			fm.validBlocks = common.Range[uint64]{}
			continue
		}
		fm.validBlocks = fm.validBlocks.Intersection(f.indexedRange.blocks)
	}
}
